docs/supported-sources/snowflake.md

Please refer to this [https://github.com/snowflakedb/snowflake-connector-python/issues/1364#issuecomment-1335942701](url) for the fix

updated snowflake account identifier usage

---

README.md
docs/.vitepress/config.mjs
docs/supported-sources/klaviyo.md
ingestr/src/klaviyo/_init_.py
ingestr/src/klaviyo/client.py
ingestr/src/sources.py

In this PR, documentation for Klaviyo is added.

Klaviyo documentation

---

README.md
docs/.vitepress/config.mjs
docs/supported-sources/adjust.md
ingestr/src/adjust/_init_.py
ingestr/src/adjust/helpers.py
ingestr/src/factory.py
ingestr/src/sources.py
pyproject.toml

Below are changes made in this PR:
- added adjust as a new source
- added campaigns as a resource

Introduce Adjust as new source

---

README.md
docs/.vitepress/config.mjs
docs/supported-sources/appsflyer.md
ingestr/src/adjust/_init_.py
ingestr/src/adjust/helpers.py
ingestr/src/appsflyer/_init_.py
ingestr/src/appsflyer/client.py
ingestr/src/factory.py
ingestr/src/sources.py
pyproject.toml
requirements.txt

Below Changes are made in this PR:
-added Appsflyer as a source
-added campaigns and creatives as a resources

Appsflyer as a source

---

docs/supported-sources/gsheets.md
ingestr/src/sources.py

Below changes are done in this PR:
- Corrected the arguments for spreadsheet_url_or_id and range_names
- added example in doc

Fix table builder argument 

---

docs/supported-sources/zendesk.md

Clarified Zendesk authentication methods

Update zendesk doc

---

README.md
docs/getting-started/quickstart.md

docs: add recommendation for using uv for installation

---

docs/.vitepress/config.mjs
docs/supported-sources/athena.md
ingestr/src/destinations.py

Following changes are made in this PR:
- Set the dataset and table name
- Set the table format to Iceberg
- Changed Athena to AWS Athena

Bug Fix - Athena

---

docs/supported-sources/adjust.md
docs/supported-sources/gorgias.md
docs/supported-sources/gsheets.md
docs/supported-sources/kafka.md
docs/supported-sources/klaviyo.md
docs/supported-sources/notion.md
docs/supported-sources/shopify.md
docs/supported-sources/stripe.md
docs/supported-sources/zendesk.md
ingestr/src/chess/__init__.py
ingestr/src/hubspot/__init__.py
ingestr/src/sources.py
ingestr/src/stripe_analytics/__init__.py
ingestr/src/zendesk/__init__.py

- replaced the schema name to ensure the database name and schema are different in docs.
- airtable does not support incremental updates so correct the typo and set incremental to false.
- set nesting level to 0 for sources.

Documentation Updates and Configuration fixes

---

docs/.vitepress/config.mjs
docs/supported-sources/applovin.md
ingestr/src/applovin/__init__.py
ingestr/src/factory.py
ingestr/src/sources.py

URI Format:
```
applovin://?api_key=<api_key>
```
supported tables:
* `publisher-report`
* `advertiser-report`
* `advertiser-probabilistic-report`
* `advertiser-ska-report`
By default, `applovin` loads data for TODAY() - 1

Applovin Source

---

ingestr/main_test.py
ingestr/src/applovin/__init__.py

I've only added basic sanity tests for now (input validation).

Applovin: Enhancements + Tests

---

ingestr/src/factory.py
requirements.txt

Closes #134 
URI
```
databricks://token:<access_token>@<server_hostname>?http_path=<http_path>&catalog=<catalog>&schema=<schema>
```

sources: add databricks

---

.gitignore
docs/.vitepress/config.mjs
docs/supported-sources/frankfurter.md
ingestr/src/factory.py
ingestr/src/frankfurter/__init__.py
ingestr/src/frankfurter/helpers.py
ingestr/src/sources.py

Integrated frankfurter.dev as a new a source. 
In src/frankfurter/__init__ I implemented 3 tables as dlt-resources which show the following: available currencies, latest exchange rates and historical exchange rates. 
In src/frankfurter/helpers I added the validation checks for query inputs.
I also updated src/sources and src/factory accordingly to integrate the new source.

added frankfurter.dev as source

---

ingestr/src/hubspot/__init__.py
ingestr/src/hubspot/helpers.py
ingestr/src/hubspot/settings.py
ingestr/src/sources.py

```
--source-table 'custom:<object>'
for example: --source-table 'custom:license'
```

add custom table to hubspot

---

ingestr/main.py
ingestr/src/collector/spinner.py

This PR is one of the many steps for making ingestr start doing stuff faster.

import larger libs lazily

---

ingestr/src/sources.py

This small PR fixes the error message to evaluate the table in the text.

fix: display table in error message

---

docs/supported-sources/airtable.md
docs/supported-sources/athena.md
ingestr/main_test.py
ingestr/src/airtable/__init__.py
ingestr/src/destinations.py
ingestr/src/sources.py
requirements.in
requirements.txt
requirements_arm64.txt

This PR bumps dlt to v1.10 to utilize the new file layout in S3 in Athena. While on it, I also did a couple of small touches on the Airtable source to standardize its behavior.

chore/upgrade dlt to v1.10

---

ingestr/src/mongodb/__init__.py
ingestr/src/mongodb/helpers.py

This is a copy paste directly from the dlt source code, no need for extra reviews on the code itself.

patch: upgrade source code with the latest in dlt

---

Makefile

Reverts bruin-data/ingestr#233

Revert "fix: setup venv in make deps as well"

---

styles/config/vocabularies/bruin/accept.txt

There was another small fix that might be usefull?

Add CrateDB to vocabularies

---

docs/supported-sources/github.md
ingestr/src/github/__init__.py
ingestr/src/github/helpers.py

Following changes are made in this PR:
-added primary key to resources
-update doc

github: update doc

---

docs/supported-sources/mongodb.md
ingestr/main.py
ingestr/main_test.py
ingestr/src/facebook_ads/__init__.py
ingestr/src/github/__init__.py
ingestr/src/github/helpers.py
ingestr/src/influxdb/__init__.py
ingestr/src/mongodb/__init__.py
ingestr/src/mongodb/helpers.py
ingestr/src/sources.py

This PR introduces a new custom aggregation support in MongoDB.

add custom table support for mongodb

---

docs/supported-sources/linear.md
ingestr/src/linear/__init__.py
requirements.txt

edit docs for unavailable source tables

Updated docs and source tables

---

docs/supported-sources/salesforce.md
ingestr/src/salesforce/__init__.py
ingestr/src/sources.py

Following changes are made in this PR:
- resolve Salesforce authentication by adding domain parameter
- added primary key to merge strategy resources
-  updated documentation based on above changes

Fix Salesforce authentication 

---

README.md
docs/supported-sources/trino.md
ingestr/src/destinations.py
ingestr/src/factory.py
requirements.in
requirements.txt
requirements_arm64.txt

This PR introduces support for Trino both as a source and a destination. It closes #372.

add support for trino as a source and a destination
