docs/.vitepress/config.mjs, docs/supported-sources/kafka.md, ingestr/main_test.py, ingestr/src/.gitignore, ingestr/src/factory.py, ingestr/src/kafka/__init__.py, ingestr/src/kafka/helpers.py, ingestr/src/sources.py, pyproject.toml, requirements.txt
This PR adds support for Kafka as a source for ingestr. With this change, ingestr can be used to get data from Kafka into the data warehouse with a single command.
=> Kafka integration

.githooks/pre-commit-hook.sh, .github/workflows/secrets-scan.yml, .gitleaksignore, Makefile, README.md
**Summary**
Adds a new make target called `setup` for installing a `pre-commit` hook that runs [gitleaks](https://github.com/gitleaks/gitleaks?tab=readme-ov-file) to ensure that developers don't commit sensitive credentials.
This PR also adds a CI job that runs `gitleaks` to enforce secret scanning on both ends.
**Prerequisites**
Gitleaks or Docker is required. The hook reports an error message in case neither are available.
**Other information**
Gitleaks detected a couple of secrets that are in the codebase right now. 2 were in testdata and 1 in telemetry module.
=> Add git hook for vulnerability scanning

Makefile, ingestr/main.py
**Summary**
Adds a new event type `command_running` with parameters:
```json
{
"command": "ingest",
"source_type": "<db type>",
"destination_type": "<db type>"
}
```
**Thoughts**
I'm not sure if `command_running` is the right event type to use for this use case. Ideas and feedback welcome!
=> Telemetry: add tracking for source and destination types

docs/.vitepress/config.mjs, docs/supported-sources/custom_queries.md, ingestr/main_test.py, ingestr/src/sources.py
This PR adds experimental support for a new `query:<query-here>` table format for SQL sources. It is quite hacky, but got the job done, so I'll release this to test it a bit more in the wild.
=> add experimental support for custom queries

.githooks/pre-commit-hook.sh
We were leaving old (dead) docker containers after running gitleaks.
added `--rm` flag to clean them up.
=> githooks: gitleaks: clean up docker container

ingestr/main_test.py, ingestr/src/appstore/__init__.py
When bruin-cli invokes ingestr, it passes it a timezone aware start/end date.
This causes an issue when we filter dates returned from `list report instances` API, because those objects are timezone-naive.
=> appstore: strip timezone from start/end date

docs/.vitepress/config.mjs, docs/supported-sources/gcs.md, docs/supported-sources/s3.md, ingestr/main_test.py, ingestr/src/factory.py, ingestr/src/filesystem/__init__.py, ingestr/src/sources.py, requirements.txt
```
gs://bucket_name?credentials_path=/path/to/service_account.json
```
This source can accept file paths either in the URI, or via `--source-table`.
For example, the following two command lines are equivalent
```
ingestr ingest --source-uri "gs://example/data/file.csv" [... other flags ...]
```
```
ingestr ingest --source-uri "gs://example" --source-table "/data/file.csv" [... other flags ...]
```
Originally, I had intended to only allow file paths in `--source-table`. However, `s3` source uses the convention of requiring file paths in URIs. I wanted to not break expectations of users who are used to that source. Hence I decided that as a middle ground:
* we will allow both forms
* only the `--source-table` form is documentated. Discouraging new users from using the old syntax.
This PR …
=> Google Cloud Storage source

docs/supported-sources/gcs.md, docs/supported-sources/s3.md, ingestr/main_test.py, ingestr/src/blob.py, ingestr/src/errors.py, ingestr/src/sources.py
This adds a backward compatiable change in uri/source table schema. The prefererred form for specifying the bucket and file path is now:
```
--source-table "bucket-name/path/to/file"
```
Older formats are still supported, but have a deprecation warning. Docs prescribe the use of the new format, and don't mention the old ones.
=> GCS+S3: support bucket name in source table

package-lock.json, package.json
This mitigates CVE-2025-24010 vulnerability.
=> deps: bump vitepress version to 1.6.3

ingestr/main_test.py, ingestr/src/destinations.py
`dlt` has switched from using gzipped `jsonl` to `parquet` for temporary staging files. (Or it could be a change in default staging format).
I've updated the destination to read the parquet files and added a test to catch these sorts of issues in the future.
=> Bugfix: CSV Destination

docs/supported-sources/clickhouse.md, ingestr/src/factory.py, ingestr/src/sources.py
Users can load data from a ClickHouse database to a  desired destination.
- source_uri = clickhouse://username:password@host:port?secure
- By default, secure=1.
=> add clickhouse as a source

ingestr/src/destinations.py, ingestr/src/loader.py, ingestr/src/loader_test.py
This change adds support for 3 of the 4 DLT [loader file](https://dlthub.com/docs/dlt-ecosystem/file-formats) formats to CSV Destination.
`INSERT` file format is currently not supported. Partly due to complexity involved and also because at this point it's unclear if any destinations/sources actually use it as their preferred loader file format.
All loaders implement streaming, so it's safe to load large files, at the cost of write throughput.
=> CSV Destination: use file-type specific loader

.gitignore, ingestr/main_test.py, pyproject.toml
the `.gitignore` file is used by build system in non intuitive ways that makes it difficult to ship it.
Even when shipped as part of the distribution, pip will ignore the file when installing the package due to gitignore.
This change removes the buildinfo file from the gitignore, and instead uses a test to catch erronous buildinfo commits to our VCS.
=> version: use alternative baby proofing measure for version file.

ingestr/main_test.py, ingestr/src/factory.py, ingestr/src/personio/__init__.py, ingestr/src/personio/helpers.py, ingestr/src/sources.py
Remove empty fields when emitting data to DLT.
This addresses a bug in `dlt` for csv data where a column is missing a value. When the type is set to `float`, dlt treats the empty field as a text value and creates a different column.
=> sources: csv: remove empty columns from rows

ingestr/main.py, ingestr/src/partition.py, ingestr/src/resource.py
This PR adds support for partitioning athena tables.
`--partition-by` specifies which column is used as the partitioning column. If the data type of the partition column is `date` or `timestamp` then the partitioning happens on a `day` interval. Otherwise, the table is partitioned on the value of the column.
For inferring the data type, both source type hints and `--columns` hints are referenced. Source hints take precedence over command line column hints.
=> Athena: Add support for partitioning

ingestr/src/hubspot/helpers.py
HubSpot returns a bunch of associations as an object, each having a key per type of association, and values as a list. 
There was a bug in the code that standardized these, and a piece of code that was supposed to be within the loop was left outside, meaning it worked only for the last item in the list. This PR fixes it. I tested it manually.
=> fix association handling

ingestr/src/adjust/adjust_helpers.py, ingestr/src/applovin_max/__init__.py, ingestr/src/appsflyer/client.py, ingestr/src/klaviyo/_init_.py, ingestr/src/linkedin_ads/helpers.py, ingestr/src/tiktok_ads/tiktok_helpers.py
Adjust support suggests 1000 seconds for the timeout, so I went ahead and removed all the other timeouts as well, which would bump them up to the default, which is 60 seconds.
=> bump timeouts across all HTTP clients

requirements.in, requirements.txt, requirements_arm64.txt
redshift_connector was causing security warnings. Now deleted the unused connector (connections to redshift are handled by psycopg2).
=> Deleted redshift_connector to Resolve Dependabot Warning

docs/supported-sources/kinesis.md, ingestr/src/kinesis/__init__.py, ingestr/src/kinesis/helpers.py
Dear @karakanb,
thanks a stack for starting ingestr. This patch brings in a minor improvement to address a Kinesis stream by ARN instead of name, like using `arn:aws:kinesis:eu-central-1:842404475894:stream/test` instead of just using `test`.
The patch was too lazy to introduce a dedicated parameter, so it modifies just a few bits to optionally accept a [StreamARN](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_StreamDescription.html#Streams-Type-StreamDescription-StreamARN) into the existing `stream_name` parameter without much ado. Do you think it's ok doing it like this? We think it offers excellent usability without needing to introduce yet another parameter.
With kind regards,
Andreas.
- https://github.com/hampsterx/async-kinesis/pull/39
=> Kinesis: Optionally address streams per StreamARN

ingestr/src/sources.py
This requoting breaks when the access or secret key contains `/`. Bruin CLI already encodes the URI, so we don't need to escape it again.
=> s3/dynamodb: don't re-quote URI during parsing

docs/supported-sources/mssql.md, ingestr/src/destinations.py, ingestr/src/sources.py
This change extends SQL Server source and destination to accept access token generated by `az` cli.
We re-purpose the deprecated `ActiveDirectoryAccessToken` Authentication parameter as an indication that the password is a token.
example:
```bash
TOKEN=$(az account get-access-token --resource https://database.windows.net/ --query accessToken -o tsv)
USER=$(az account show --query user.name -o tsv)
SERVER="sql-server-expo"
DB="ingestr"
CONN_STR="mssql://$USER:$TOKEN@$SERVER.database.windows.net/$DB?driver=ODBC+Driver+18+for+SQL+Server&authentication=ActiveDirectoryAccessToken&encrypt=yes"
python3 -m ingestr.main ingest \
--source-uri "$CONN_STR" \
--source-table "dbo.example" \
--dest-uri "$CONN_STR" \
--dest-table "dbo.example_3" \
--yes
```
=> mssql:  add support for token auth

requirements.in, requirements.txt, requirements_arm64.txt
When using `uv pip install --upgrade ingestr`, only version v0.13.52 gets installed.
Adding support for CrateDB as a source adapter per GH-232 added the dependency `sqlalchemy-cratedb==0.42.0.dev2`, which is apparently problematic in some cases.
- https://github.com/crate-workbench/ingestr/issues/1#issuecomment-3033703828
To install the latest version of ingestr with `sqlalchemy-cratedb==0.42.0.dev2` successfully, `uv` needs the `--prerelease=allow` option. Otherwise, it will install the much older ingestr version v0.13.52.
Downgrade to a previous GA version of sqlalchemy-cratedb (v0.41.0), to mitigate any such obstacles.
Note to self: We'll need to wrap up another patch'es ingredients to fully conclude the operation making 0.42.0 available.
- …
=> Dependencies: Downgrade to `sqlalchemy-cratedb==0.41.0` GA

ingestr/src/applovin_max/__init__.py
Add `platform` field to AppLovin Max source data to allow distinguishing between Android, iOS, and FireOS.
Although the AppLovin Max source already separates data by platform internally, this information was not included in the final yielded data, making it impossible to distinguish platforms in the resulting table.
---
[Slack Thread](https://bruintalk.slack.com/archives/C066JBNP3U2/p1751991433070039?thread_ts=1751991433.070039&cid=C066JBNP3U2)
=> Add platform field to applovin max data

ingestr/src/linear/__init__.py, ingestr/src/linear/helpers.py, ingestr/src/stripe_analytics/helpers.py, ingestr/src/zoom/__init__.py, ingestr/src/zoom/helpers.py
That's just a little maintenance patch to retroactively refresh code formatting, so it's no longer in the way again and again when working on other patches.
=> Chore: Format code using `make lint-ci`

ingestr/src/destinations.py, ingestr/src/destinations_test.py, requirements.in, requirements.txt, requirements_arm64.txt
Following changes are made in this PR:
- Pass credentials via a creds dict instead of the URI to resolve TypeError.
- Use the schema from the URI as dataset_name instead taking from the dest-table to avoid overriding the schema.
- Upgrade databricks-sql-connector from 2.9.3 to 4.0.5 to fix issues with handling NULL values.
- Update test function accordingly
Tested Databricks as both a source and a destination - working fine.
=> fix databricks destination

requirements.in, requirements.txt, requirements_arm64.txt
That's a very minor version bump of a dependency package.
- https://github.com/crate/dlt-cratedb/releases/tag/v0.0.2
- GH-289
=> Dependencies: Update to `dlt-cratedb==0.0.2`

.github/workflows/release.yml
arm emulation of amd64 is much more optimised than amd64 emulation of arm architecture.
This change slows down amd64 builds by 20% but speeds up arm build by a whooping 12x
At that rate, the bottle necks become our tests, not the builds.
=> ci: release: use arm runner for building docker images
